# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1  # Use the latest valid version for flake8
    hooks:
      - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0
  hooks:
    - id: mypy
      args: ["--ignore-missing-imports", "--strict"]
      additional_dependencies: [pandas, matplotlib, numpy, seaborn]
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.0
  hooks:
    - id: nbstripout
